services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: scryptan/versus:debug
    environment:
      DbConnectionString: "Host=postgres;Port=5435;Database=kot;Username=kot;Password=kot"
      JwtKey: "rinatgilemshin24122003fdgdfgdfgfdgdfgdfgdfgfdgdfg"
      POSTGRES_USER: "kot"
      POSTGRES_PASSWORD: "kot"
      PGPORT: 5435
    ports:
      - "4000:4000"
    volumes:
      - ./data/images:/app/wwwroot/images
  
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: "kot"
      PGPORT: 5435
      POSTGRES_USER: "kot"
      POSTGRES_PASSWORD: "kot"
    ports:
      - "5435:5435"
    volumes:
      - ./data/db:/var/lib/postgresql/data